🐛 Check lock files at installation

diff --git a/Auto-Devops/NodeJS.gitlab-ci.yml b/Auto-Devops/NodeJS.gitlab-ci.yml
--- a/Auto-Devops/NodeJS.gitlab-ci.yml
+++ b/Auto-Devops/NodeJS.gitlab-ci.yml
@@ -32,6 +32,12 @@ nodejs:install:
     - !reference [.nodejs_cache_push, cache]
   script:
     - |
+      # Check lock files
+      if [[ -f yarn.lock && -f package-lock.json ]]; then
+        >&2 echo "Error: Duplicate lockfile. Either `package-lock.json` or `yarn.lock` should be removed."
+        exit 1
+      fi
+    - |
       # Case Yarn Berry
       if [[ -f yarn.lock && -d .yarn/releases ]]; then
         yarn install --immutable;
